name: Build

on:
  pull_request:
    paths:
      - '**.ino'
      - '**.cpp'
      - '**.h'
      - '**.yml'
  push:
    paths:
      - '**.ino'
      - '**.cpp'
      - '**.h'
      - '**.yml'
  schedule:
    - cron: "0 11 13 */2 *"

env:
  ARTIFACT_FOLDER: artifact

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Compile sketches
        uses: arduino/compile-sketches@v1
        with:
          fqbn: esp32:esp32:esp32
          platforms: |
            - name: esp32:esp32
              source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          sketch-paths: |
            - beastie.ino
          libraries: |
            - name: Watchy
              version: latest
            - name: GxEPD2
              version: latest
          cli-compile-flags: |
            - --export-binaries
            - --build-property
            - build.partitions=min_spiffs
            - --build-property
            - upload.maximum_size=1966080
          enable-deltas-report: true
      - name: Prepare the artifact
        run: mkdir "${FOLDER}" && mv "build/esp32.esp32.esp32/${SKETCH}.ino.bin" "${FOLDER}/${SKETCH}.bin"
        env:
          FOLDER: ${{ env.ARTIFACT_FOLDER }}
          SKETCH: ${{ github.event.repository.name }}
      - name: Get the short Git SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo "${GITHUB_SHA}" | cut -c1-7)"
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-${{ steps.slug.outputs.sha7 }}
          path: ${{ env.ARTIFACT_FOLDER }}
